name: FirstPlugin
version: 1.0-SNAPSHOT
main: org.pluginmakers.firstplugin
author: SageFlame161810
api-version: 1.21.4

softdepend: [PlaceholderAPI]

commands:
  fly:
    permission: "firstplugin.fly"
    description: Makes you fly
    aliases:
      - flight
      - f

  healthscale:
    permission: "firstplugin.healthscale"
    description: Changes the max amount of hearts you have
    aliases:
      - hs

  testplaceholders:
    permission: "firstplugin.testing"
    description: Test any or all custom placeholders
    aliases:
      - testp
      - ptest
      - placeholdertest

  killgui:
    permission: "firstplugin.testing"
    description: Opens a gui that can kill you

  skin:
    description: Change your skin
    usage: /skin <playername>

  vanish:
    description: Vanish yourself or any player
    permission: "firstplugin.vanish"

  blockpro:
    description: Allows you to disable or enable block protection
    permission: "firstplugin.breakblocks"

permissions:
  firstplugin.breakblocks:
    description: Allows breaking blocks
    default: op

  firstplugin.testing:
    description: Allows permission to testing commands
    default: op

  firstplugin.healthscale:
    description: Allows you to change your health using the /healthscale command
    default: op

  firstplugin.fly:
    description: Allows you to use the /fly command
    default: op

  firstplugin.vanish:
    description: Allows you to use the /vanish command
    default: op
