# Trigger this workflow on release
on:
  release:
    types: [published]
  workflow_dispatch:

# Make sure the GITHUB_TOKEN has permission to upload to our releases
permissions:
  contents: write
  packages: write

... SOME OTHER STUFF GOES HERE ...

# Build the FeedMD CLI utility, and upload to the release that triggered the workflow 
- name: 'Create package release and deploy to package index'
  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

    'Create Release':
      runs-on: ubuntu-latest
      steps:
      - name: Create release
        run: |
          cd /home/runner/work/coolplugin/coolplugin/target
          gh release upload ${{github.event.release.tag_name}} firstplugin-1.0.1-SNAPSHOT.jar        
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash

    'Deploy to github packages':
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
